name: CI-docker
run-name: ${{ github.actor }} is running CI-docker

on:
  push:
    branches: [production]

jobs:
  build:
    name: Verify Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t monorepoonfire:ci-check .
