name: CI-dev
description: |
  This workflow runs on pushes to the 'dev' branch, installs dependencies, builds the project, and runs devs using pnpm.

on:
  push:
    branches: [dev]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      ENV: ${{ vars.vars }}
      PORT: ${{ vars.PORT }}
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}
      DATABASE_URL: ${{ vars.DATABASE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Print environment variables
        run: |
          echo "NODE_ENV: $NODE_ENV"
          echo "ENV: $ENV"
          echo "PORT: $PORT"
          echo "LOG_LEVEL: $LOG_LEVEL"
          echo "DATABASE_URL: $DATABASE_URL"
          echo "TURBO_TOKEN: $TURBO_TOKEN"
          echo "TURBO_TEAM: $TURBO_TEAM"

      - name: Run tests
        run: pnpm run test

      - name: Run build
        run: pnpm run build
