name: CI-dev
run-name: ${{ github.actor }} is running CI-dev
description: |
  This workflow runs on pushes to the 'dev' branch, installs dependencies, builds the project, and runs devs using pnpm.

on:
  push:
    branches: [dev]

jobs:
  create-dotenv:
    name: create environment file
    runs-on: ubuntu-latest
    # Use the environment specified by the caller (so it pulls the right variables)
    environment: env
    env:
      ENV: ${{ vars.ENV }}
      PORT: ${{ vars.PORT }}
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      # creates the directory app/hono/src/environment if it does not already exist.

      # The -p flag means "no error if existing, make parent directories as needed."
      # This ensures that the folder structure is present before writing the .env file into it.
      - name: Create environment directory
        run: mkdir -p app/hono/src/environment

      - name: Print environment variables
        run: |
          echo "ENV: $ENV"
          echo "PORT: $PORT"
          echo "LOG_LEVEL: $LOG_LEVEL"
          echo "DATABASE_URL: $DATABASE_URL"

      # Write environment variables from GitHub environment to the specified .env file
      - name: Create .env file
        run: |
          echo "Creating .env file: app/hono/src/environment/.env"
          echo "ENV=${{ vars.ENV }}, PORT=${{ vars.PORT }}, LOG_LEVEL=${{ vars.LOG_LEVEL }}, DATABASE_URL=${{ secrets.DATABASE_URL }}"
          echo "ENV=${{ vars.ENV }}" >> app/hono/src/environment/.env
          echo "PORT=${{ vars.PORT }}" >> app/hono/src/environment/.env
          echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}" >> app/hono/src/environment/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> app/hono/src/environment/.env
          
      - name: Upload .env as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hono-env
          path: app/hono/src/environment/.env

  build:
    needs: create-dotenv
    name: test and build
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download .env artifact
        uses: actions/download-artifact@v4
        with:
          name: hono-env
          path: app/hono/src/environment/

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      # Debug: print the .env file before running tests
      - name: Print .env file for debugging
        run: cat app/hono/src/environment/.env

      - name: Run tests
        run: pnpm run test

      - name: Run build
        run: pnpm run build
