name: CI-production
run-name: ${{ github.actor }} is running CI-production

on:
  push:
    branches: [production]

jobs:
  build:
    name: Migrate and Build
    runs-on: ubuntu-latest
    environment: env.production
    env:
      ENV: ${{ vars.ENV }}
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create environment directory
        run: mkdir -p app/hono/src/environment

      - name: Create .env.production file
        run: |
          echo "ENV=${{ vars.ENV }}" > app/hono/src/environment/.env.production
          echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}" >> app/hono/src/environment/.env.production
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> app/hono/src/environment/.env.production
          echo "DATABASE_AUTH_TOKEN=${{ secrets.DATABASE_AUTH_TOKEN }}" >> app/hono/src/environment/.env.production

      - name: Run database migrations
        run: pnpm --filter @app/hono db:migrate:production

      - name: Run build
        run: pnpm run build:production
