name: Create environment file

on:
  # This workflow is designed to be called from other workflows (reusable workflow)
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string # The name of the GitHub Actions environment to use (e.g., dev, test, production)
      env_file:
        required: true
        type: string # The name of the .env file to create (e.g., .env, .env.test, .env.production)

jobs:
  create-dotenv:
    runs-on: ubuntu-latest
    # Use the environment specified by the caller (so it pulls the right variables)
    environment: ${{ inputs.env_name }}
    steps:
      # creates the directory src/environment if it does not already exist.

      # The -p flag means "no error if existing, make parent directories as needed."
      # This ensures that the folder structure is present before writing the .env file into it.
      - name: Create environment directory
        run: mkdir -p src/environment

      - name: Print environment variables
        run: |
          echo "ENV: $ENV"
          echo "PORT: $PORT"
          echo "LOG_LEVEL: $LOG_LEVEL"
          echo "DATABASE_URL: $DATABASE_URL"

      # Write environment variables from GitHub environment to the specified .env file
      - name: Create .env file
        run: |
          echo "Creating environment variables for ${ inputs.env_name }"
          echo "Creating .env file: src/environment/${{ inputs.env_file }}"
          echo "ENV=${{ vars.ENV }}" >> src/environment/${{ inputs.env_file }}
          echo "PORT=${{ vars.PORT }}" >> src/environment/${{ inputs.env_file }}
          echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}" >> src/environment/${{ inputs.env_file }}
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> src/environment/${{ inputs.env_file }}
          echo "DATABASE_AUTH_TOKEN=${{ secrets.DATABASE_AUTH_TOKEN }}" >> src/environment/${{ inputs.env_file }}

      # Upload the generated .env file as an artifact so
